# Generated by Django 2.2.6 on 2019-10-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
